# Highlights

- id: doi:10.1038/s41588-023-01395-x
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1038%2Fs41588-023-01395-x/MediaObjects/41588_2023_1395_Fig5_HTML.png?as=webp
  buttons:
    - type: source
      text: Code Availablility
      link: https://zenodo.org/record/7783022
    - type: website
      text: Data Navigator
      link: https://papaemmelab.github.io/neuroblastoma-clonality-viewer
    - type: data
      text: Data Access
      link: https://www.ncbi.nlm.nih.gov/projects/gap/cgi-bin/study.cgi?study_id=phs003111.v1.p1
  tags:
    - Neuroblastoma
    - Evolution
    - Metastasis
  
- id: doi:10.1056/EVIDoa2200008
  image: https://evidence.nejm.org/cms/10.1056/EVIDoa2200008/asset/d8ce4ec7-ad33-4079-80b1-16ed8293e330/assets/images/large/evidoa2200008_f2.jpg
  buttons:
    - type: app
      text: Calculator
      link: http://www.mds-risk-model.com
    - type: package
      text: R Package
      link: https://github.com/papaemmelab/ipssm
    - type: server
      text: API
      link: http://api.mds-risk-model.com
  tags:
    - MDS
    - Cancer
    - Hematology
  repo: papaemmelab/ipssm

- id: doi:10.1038/s41467-022-30233-7
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1038%2Fs41467-022-30233-7/MediaObjects/41467_2022_30233_Fig1_HTML.png?as=webp
  tags:
    - Pediatrics
    - Whole Genome Sequencing
    - Isabl

- id: doi:10.1186/s12859-020-03879-7
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1186%2Fs12859-020-03879-7/MediaObjects/12859_2020_3879_Fig1_HTML.png?as=webp
  buttons:
    - type: docs
      text: Documentation
      link: https://docs.isabl.io
  tags:
    - Platform
    - Bioinformatics
    - Biobank

- id: doi:10.1038/s41591-020-1008-z
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1038%2Fs41591-020-1008-z/MediaObjects/41591_2020_1008_Fig1_HTML.png?as=webp

- id: doi:10.1038/s41467-022-32103-8
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1038%2Fs41467-022-32103-8/MediaObjects/41467_2022_32103_Fig3_HTML.png?as=webp

- id: doi:10.1056/NEJMoa1516192
  image: https://www.nejm.org/na101/home/literatum/publisher/mms/journals/content/nejm/2016/nejm_2016.374.issue-23/nejmoa1516192/20180329/images/img_medium/nejmoa1516192_f2.jpeg

- id: doi:10.1182/blood-2011-09-377275
  image: https://ash.silverchair-cdn.com/ash/content_public/journal/blood/118/24/10.1182_blood-2011-09-377275/4/zh89991182640003.jpeg?Expires=1750873086&Signature=s5jbjAuBGLNGqFP6hX-pH61bF2wAeDhzrFYY4nuElzQbLPmjQGIvg4yaFF6WrJ1WO6om7inUE7yRttUCif87Ky0nBys~N-PSsM3rgvMD~syK4mdjIwu8GAEgGeR3I5xPSVr3RtaJOvYGVnoe7Jcal7pPbK4obQQfPNrjRMX4C1tpeMuJ7TnyGdY3r5mOfISOqtkOqw9dKuUfpg7euadeGl50KECrQaQ6IYT0GpL15Rm7DOrF26RDOz-HiAQ5mbfXTTgTa1l26JlV-LqtXtXejaJg00GKGkLCUovdEqOdjEQHzzCjbDCAOyWFkA~7JGDadDX4XgBG1EzQKgfCseY7rw__&Key-Pair-Id=APKAIE5G5CRDK6RD3PGA

- id: doi:10.1056/NEJMoa2413361
  image: https://www.nejm.org/cms/10.1056/NEJMoa2413361/asset/300a8e4c-b560-4e67-9fcd-83b7caf7746c/assets/images/large/nejmoa2413361_f1.jpg

- id: doi:10.1038/s41588-020-00710-0
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1038%2Fs41588-020-00710-0/MediaObjects/41588_2020_710_Fig1_HTML.png?as=webp

# Rest of sources

- id: doi:10.1038/ncomms6901

- id: doi:10.1093/bioinformatics/btt750

- id: doi:10.1182/blood-2013-08-518886

- id: doi:10.1038/ng.430

- id: doi:10.1182/bloodadvances.2021006325

- id: doi:10.1038/ng.2874

- id: doi:10.1038/s41375-022-01537-w

- id: doi:10.1038/s41375-021-01448-2

- id: doi:10.3324/haematol.2021.279177

- id: doi:10.1056/NEJMoa1412098

- id: doi:10.3324/haematol.2014.113381

- id: doi:10.1182/blood-2014-06-579466

- id: doi:10.1038/leu.2014.161

- id: doi:10.1038/leu.2014.331

- id: doi:10.1182/blood-2014-09-603043

- id: doi:10.7554/eLife.02935

- id: doi:10.1182/blood-2014-03-560227

- id: doi:10.1126/science.1251343

- id: doi:10.1016/j.ccr.2014.03.036

- id: doi:10.1038/ng.2955

- id: doi:10.1038/ncomms4644

- id: doi:10.1038/nature13115

- id: doi:10.1038/ng.2921

- id: doi:10.1038/ng.2846

- id: doi:10.1056/NEJMoa1312542

- id: doi:10.1101/gr.159913.113

- id: doi:10.1038/nature12477

- id: doi:10.1172/JCI67201

- id: doi:10.1038/leu.2012.298

- id: doi:10.3324/haematol.2012.077446

- id: doi:10.1038/ng.2495

- id: doi:10.1016/j.cell.2012.04.024

- id: doi:10.1016/j.cell.2012.04.023

- id: doi:10.1038/nature11017

- id: doi:10.1056/NEJMoa1103283

- id: doi:10.1182/blood-2010-08-301598

- id: doi:10.1182/blood-2009-09-244483

- id: doi:10.1038/ng.585

- id: doi:10.1182/blood-2009-09-241513

- id: doi:10.1038/ejhg.2008.129

- id: doi:10.1111/j.1365-2141.2008.07188.x

- id: doi:10.1182/blood.2023023727
  image: https://ash.silverchair-cdn.com/ash/content_public/journal/blood/144/15/10.1182_blood.2023023727/3/blood_bld-2023-023727-ga1.jpeg?Expires=1750156385&Signature=p6D8N67NMlMypqgI~t-jzrNtRh5H3meMZ1DAICUV7jDCYzLCLW9gu3Tq-qtlWY8Vk3iOKMahW3u-Nbth-DVC9HbCPvrn1di2duLRG~uwOcmjVY6J-XhjadOl0UjdJQRYDjitsZJHGlPRSIeBbixGVvdOSk1Xy0cU~9UqLhcIvGu5IFZL--bL0H0xQ8Zx9OK5op29203g7JHhxB6Wo~OSkbEORrWdOMlps0Po~s8yhq8S3l~gJKgXgRftLqgOMFQSoQjIoBo1PvmAGRaN-fK3-Iu6TQ8jc7ca8q9BxLtEKm3ob2-WbKyyPl4lts-x83JTGQ4DQgVe2vCway5q7nF6yw__&Key-Pair-Id=APKAIE5G5CRDK6RD3PGA
  # image: https://ash.silverchair-cdn.com/ash/content_public/journal/blood/144/15/10.1182_blood.2023023727/3/blood_bld-2023-023727-gr2.jpeg?Expires=1750873385&Signature=1gnS76BTNkyfmrzoNLp-QukXTTrjnGXAvdnSWgnuRYLGgNOozDvkynWUR-mCIiHgzAlynxQnP2UGXdEX2SOYEj8h7Y4MtXvr7aK~FvNP7M6dIs7ykIdI3piuYuW9o1nFi2-leDqQ5FcHjH2mXMxPvXorryTxx4qAWP47~xorLHQDGySBb-fV~3VkG9KMm7evZ6stZOIlVoA9PF72tDDTZRNvoTsAhbyi~7YZs8n-4t5i6YvQ6oz3axcCm6OZUFqF~QaL3YkccqXWX0QVaT7wx2SNMlQDwAnlSgkAFKgwxVfECadUkv8WFWlsA7H-qkAlpimefZVpuWmo-jOJfe~Qwg__&Key-Pair-Id=APKAIE5G5CRDK6RD3PGA

- id: doi:10.1182/bloodadvances.2022008992

- id: doi:10.1158/0008-5472.CAN-23-0385

- id: doi:10.1182/blood.2023023723

- id: doi:10.7326/L24-0125

- id: doi:10.1182/bloodadvances.2024014869

- id: doi:10.1016/j.stem.2025.04.012

# Jaeger E, Webb E, Howarth K, Carvajal-Carmona L, Rowan A, Broderick P, Walther A, Spain S, Pittman A, Kemp Z, Sullivan K, Heinimann K, Lubbe S, Domingo E, Barclay E, Martin L, Gorman M, Chandler I, Vijayakrishnan J, Wood W, Papaemmanuil E, Penegar S, Qureshi M; CORGI Consortium, Farrington S, Tenesa A, Cazier JB, Kerr D, Gray R, Peto J, Dunlop M, Campbell H, Thomas H, Houlston R, Tomlinson I. Common genetic variants at the CRAC1 (HMPS) locus on chromosome 15q13.3 influence colorectal cancer risk. Nat Genet. 2008 Jan;40(1):26-8
# Penegar S, Wood W, Lubbe S, Chandler I, Broderick P, Papaemmanuil E, Sellick G, Gray R, Peto J, Houlston R. National study of colorectal cancer genetics. Br J Cancer. 2007 Nov 5;97(9):1305-9
# Broderick P, Carvajal-Carmona L, Pittman AM, Webb E, Howarth K, Rowan A, Lubbe S, Spain S, Sullivan K, Fielding S, Jaeger E, Vijayakrishnan J, Kemp Z, Gorman M, Chandler I, Papaemmanuil E, Penegar S, Wood W, Sellick G, Qureshi M, Teixeira A, Domingo E, Barclay E, Martin L, Sieber O; CORGI Consortium, Kerr D, Gray R, Peto J, Cazier JB, Tomlinson I, Houlston RS. A genome-wide association study shows that common alleles of SMAD7 influence colorectal cancer risk. Nat Genet. 2007 Nov;39(11):1315-7
# Kemp Z, Carvajal-Carmona L, Spain S, Barclay E, Gorman M, Martin L, Jaeger E, Brooks N, Bishop DT, Thomas H, Tomlinson I, Papaemmanuil E, Webb E, Sellick GS, Wood W, Evans G, Lucassen A, Maher ER, Houlston RS; ColoRectal tumour Gene Identification (CoRGI) Study Consortium. Evidence for a colorectal cancer susceptibility locus on chromosome 3q21-q24 from a high-density SNP genome-wide linkage scan. Hum Mol Genet. 2006 Oct 1;15(19):2903-10
